// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import Home from "./Home/Home";
// import "bootstrap/dist/css/bootstrap.min.css";

// export default function Main() {
//   return (
//     <>
//       <Home />
//     </>
//   );
// }
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Home from "./Home/CommunityPage";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Main() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home />
      </main>

    
    </div>
  )
}